name: 'CD test - master branch'

on:
  push:
    branches:
      - master


jobs:
  test-feature:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Printing"
        uses: fifsky/ssh-action@master
        with:
          command: echo path sandbox ${{ secrets.DEPLOY_PATH }}
          host: amongcode.com
          user: amongcod
          key: ${{ secrets.PRIVATE_KEY }}
          args: "-tt"